version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: fighthub_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - fighthub_pg_data:/var/lib/postgresql/data

volumes:
  fighthub_pg_data: